DROP TABLE IF EXISTS foods CASCADE;
CREATE TABLE foods (
  id SERIAL PRIMARY KEY NOT NULL,
  category VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  cost SMALLINT NOT NULL,
  size VARCHAR(255) NOT NULL,
  picture VARCHAR(255)NOT NULL
);
