DROP TABLE IF EXISTS order_foods CASCADE;
CREATE TABLE order_foods (
  food_id INTEGER NOT NULL REFERENCES foods(id) ON DELETE CASCADE,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  quantity INTEGER DEFAULT 1,
  PRIMARY KEY (food_id, order_id)
);
